### ISSUE TITLE
Add support for searching for language by typing

### ISSUE THREAD

**Issue by marmeladapk** [elementary/initial-setup#102]
## Problem

Searching for your language can take a moment.

## Proposal

Usually one can search in long lists by typing first letters of your option.

## Prior Art

Firefox (and probably other web browsers) jump to option in dropdown list when typing first letters of that option.

(try it [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select), open dropdown list and type first letter of any option, this option will become selected)

**Comment by ryonakano** [comment]
I guess we don't add a search entry here because of the same reason with https://github.com/elementary/installer/pull/458#issuecomment-720907552

**Comment by marmeladapk** [comment]
Unfortunately it makes a lot of sense.
