### ISSUE TITLE
Dashes not allowed in username during installation of elementary OS 6.0

### ISSUE THREAD

**Issue by erenfro** [elementary/initial-setup#124]

**Comment by pridumkuvatyj** [comment]
The same on EOS 6.1 stable. If I enter `prid-PC` - it saves `pridPC`. I think it's the same issue: https://github.com/elementary/initial-setup/issues/135#issuecomment-1020687980

**Comment by ryonakano** [comment]
Actually dashes `–` is not allowed as a hostname, maybe you mean hyphens `-`? So renaming the issue title.
