### ISSUE TITLE
Delete a user if creation fails

### ISSUE THREAD

**Issue by danrabbit** [elementary/initial-setup#138]
### What Happened?

I set up my user and got an error that the user wasn't able to be added to the samba share. Initial setup then exited, and I was left stranded with a disabled account.

### Steps to Reproduce

No idea how to reproduce the failure, but basically failure states aren't well handled here

### Expected Behavior

We probably shouldn't exit Initial Setup here if creation fails: https://github.com/elementary/initial-setup/blob/e34c159d4e5d46b6d74a560ed59c47861c610c5a/src/MainWindow.vala#L93

And we should probably clean up any disabled/failed user accounts

### OS Version

7.x (Early Access)

### Software Version

Compiled from git

**Comment by avojak** [comment]
I'm able to reproduce this issue on a VM setup using the 20220127 daily build. 

```
GDBus.Error:org.freedesktop.Accounts.Error.Failed: failed to add user avojak to group sambashare: Child process exited with code 1
```

I'm not sure how to access any log files, but would be happy to do so if told where to look.

**Comment by ryonakano** [comment]
FYI attaching a screenshot of the error message currently shown in Initial Setup on the daily image:

![スクリーンショット 2022-01-30 135621](https://user-images.githubusercontent.com/26003928/151687401-8e8ba61e-5a97-4062-b7ce-19caada291bf.png)

**Comment by avojak** [comment]
I'm no longer seeing this error on the latest daily build (20220202)
