### ISSUE TITLE
Couldn't get permission to set hostname

### ISSUE THREAD

**Issue by danirabbit** [elementary/initial-setup#182]
### What Happened?

Initial setup couldn't get permission to name this device

### Steps to Reproduce

Run through initial setup on the latest OS 8 daily

### Expected Behavior

Could get permission to set hostname

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

**Comment by tpimont** [comment]
Hi,
Try to install Eementary 8.0 preview and get this problem .
Is there a way to bypass initial-setup while waiting for the bug to be resolved ?
