### ISSUE TITLE
Grub2 Install along with usb persistance freezing

### ISSUE THREAD

**Issue by chadlinje** [elementary/initial-setup#26]
Ive tried using disk repair .... im on a fresh laptop and wanted to install elementary os yet everytime i try to do an install via unetbootin and usb (as my laptop dosent have a dvd/cd drive).

In result im trying to install elementary os on an 8gb sandisk usb and have a little bit of persistance to see if im able to use it and access aditional storage from on my laptop yet that also freezes in unetbootin. Im tying pendrive linux now I know persistance is only working on ubuntu bit i thought it would work as it is built upon ubunti right?

**Comment by mdh34** [comment]
Closing this as it isn't related to the initial setup program, perhaps check out the [elementary OS Stack Exchange](https://elementaryos.stackexchange.com/)
