### ISSUE TITLE
Languages sorted by letter case size

### ISSUE THREAD

**Issue by donadigo** [elementary/initial-setup#47]
Languages shouldn't be sorted by the letter case size. It took me a while for searching the polish language in the languages that start with "p" only to realize that it was sorted below all languages with first capital letter.

**Comment by danrabbit** [comment]
I can't confirm this issue. Do you see something different from this?

![Screenshot from 2019-04-30 15 00 47@2x](https://user-images.githubusercontent.com/7277719/56996267-cf41c980-6b58-11e9-80ec-e8bf7671be9e.png)

**Comment by danrabbit** [comment]
Gonna close this since there was never a confirmation
