### ISSUE TITLE
Add the screenshot in the readme

### ISSUE THREAD

**Issue by ryonakano** [elementary/initial-setup#73]
The screenshot is in the repository but not in the readme

**Comment by Ananthavijay** [comment]
@ryonakano  Which screenshot should I add?

This one https://github.com/elementary/initial-setup/blob/master/data/screenshot%402x.png or this one https://github.com/elementary/initial-setup/blob/master/data/screenshot-create-account%402x.png ?

**Comment by ryonakano** [comment]
@Ananthavijay I guess either one is fine but the former one might be even better since it's the first view that users see when the Initial Setup is launched.

**Comment by Ananthavijay** [comment]
What about both?
