### ISSUE TITLE
Backports required for Hera

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/initial-setup#96]
We need to backport #93 and #95 into the stable `juno` branch (and possibly do a new release) to allow initial setup to properly set keyboard layouts and languages on new users.

We can't just directly do a new release against `master` as there's now Handy stuff that blocks this from building on Hera.

**Comment by cassidyjames** [comment]
It looks like these are still outstanding, as I don't see them in the `juno` branch.

**Comment by danrabbit** [comment]
Building into Staging first: https://code.launchpad.net/~elementary-os/+recipe/initial-setup-juno

**Comment by danrabbit** [comment]
Okay, it's building successfully, so it will go to stable!

**Comment by cassidyjames** [comment]
Thank you!
